# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'League', 'verbose_name_plural': 'Leagues'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teamstat',
            options={'verbose_name': 'Team statistic', 'verbose_name_plural': 'Teams statistics'},
        ),
        migrations.AlterField(
            model_name='match',
            name='team_guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_matches', to='fifa_league.TeamStat'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='fifa_league.TeamStat'),
        ),
        migrations.AlterField(
            model_name='teamstat',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_stat', to='fifa_league.League'),
        ),
        migrations.AlterField(
            model_name='teamstat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_stat', to='fifa_league.Team'),
        ),
    ]
