# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_league', '0004_auto_20170110_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, upload_to='delete/'),
        ),
    ]
