# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fifa_league.functions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fifa_league', '0007_auto_20170111_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='full_description',
            field=models.TextField(default='League full description'),
        ),
        migrations.AddField(
            model_name='league',
            name='short_description',
            field=models.CharField(default='League short description', max_length=250),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='league',
            name='shortcut',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(default='../static/fifa_league/gfx/user/default-avatar.svg', upload_to=fifa_league.functions.user_directory_path),
        ),
    ]
