# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_league', '0008_auto_20170111_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.FileField(default='../static/fifa_league/gfx/league/default-league-logo.svg', upload_to='uploads/leagues/logos/'),
        ),
    ]
