# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_league', '0013_auto_20170125_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'default_permissions': ('add', 'change', 'delete'), 'verbose_name': 'League', 'verbose_name_plural': 'Leagues'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'default_permissions': ('add', 'delete', 'change'), 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'default_permissions': ('add', 'change', 'delete'), 'verbose_name': 'Player'},
        ),
        migrations.AlterModelOptions(
            name='teamstat',
            options={'default_permissions': ('add', 'change', 'delete'), 'verbose_name': 'Team statistic', 'verbose_name_plural': 'Teams statistics'},
        ),
        migrations.AlterField(
            model_name='match',
            name='team_guest_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
