# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import fifa_league.functions


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_league', '0014_auto_20170126_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(default='../media/static/fifa_league/user/default-avatar.svg', upload_to=fifa_league.functions.user_directory_path),
        ),
    ]
