# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_league', '0015_auto_20170127_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.FileField(default='../media/static/fifa_league/league/default-league-logo.svg', upload_to='uploads/leagues/logos/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.FileField(default='../static/static/fifa_league/player/default-player-photo.svg', upload_to='uploads/players/photos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(default='../media/static/fifa_league/team/default-team-logo.svg', upload_to='uploads/teams/logos/'),
        ),
    ]
