# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_league', '0018_auto_20170130_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='full_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='league',
            name='short_description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
